image: python:3.9

stages:
  - code_review

code_review_merge_request:
  stage: code_review
  only:
    - merge_requests
  script:
    - pip install -r requirements.txt
    - python ai-code-review.py --event-type merge_request --merge-request-id $CI_MERGE_REQUEST_IID
  variables:
    GITLAB_URL: $GITLAB_URL
    GITLAB_PRIVATE_TOKEN: $GITLAB_PRIVATE_TOKEN
    GEMINI_API_KEY: $GEMINI_API_KEY
    #OPENAI_API_KEY: $OPENAI_API_KEY